20194294 hungtk week10
vbee-holding/20211 pull request #94
Opened 2021-12-01 10:37 UTC by 20194294-hungtk

@tuanlb-vbee  anh kiểm tra code dùm em với ạ

2021-12-01 10:45 UTC, tuanlb-vbee requested changes

2021-12-01 10:45 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/App.js
> +    <Grid container className="App">
tên class đừng viết hoa e nhé: => app

2021-12-01 10:45 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/Home.js
> +    const [openView, setView] = useState(false);
3 cái này e có thể gộp lại là: 
```javascript
const [open, setOpen] = useState({ edit: false, addNew: false, view: false });
```
với chú ý cách đặt tên, biến thì là danh từ, func thì phải là động từ nhé

2021-12-01 10:45 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/CreateData.js
> +  const [profileImage, setProfileImage] = useState('')
trời.. sao e ko đưa nó vào 1 object.. sao lại đi làm kiểu này????

2021-12-01 10:45 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/CreateData.js
> +  const [profileImage, setProfileImage] = useState('')
a review đến đây thôi.. sửa xong a reiview tiếp nhé

2021-12-01 18:46 UTC, 20194294-hungtk commented
@tuanlb-vbee  Em sửa lại mấy lỗi a bảo rồi ạ

2021-12-02 05:38 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/DataTable.js
> +  }
chú ý tái sử dụng code, URL cần là constants

2021-12-02 05:38 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/DataTable.js
> +    const result = await axios.delete("http://localhost:4000/student/" + id);
```javascript
const result = await axios.delete(`http://localhost:4000/student/${id}`);

```

2021-12-02 05:38 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/DataTable.js
> +  let i = 0, j = 0;
i với j là cái gì vậy em???

2021-12-02 05:38 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/DataTable.js
> +                <TableCell>{++i}</TableCell>
em đọc lại cách sử dụng map prototype nhé

2021-12-02 05:38 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/EditData.js
> +  const { data, open, handleClose } = props
export default function EditData({ data, open, handleClose })

2021-12-02 05:38 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/EditData.js
> +  }
destructuring

2021-12-02 05:38 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/EditData.js
> +      props.handleClose();
ở trên handleClose khai báo r mà

2021-12-02 05:38 UTC, tuanlb-vbee commented on week-10/20194294/frontend/src/component/EditData.js
> +  },[data])
data của e ở đây là student, thì ko cần phải tạo student state làm gì nữa.. cứ thế lấy mà dùng thôi.. lòng vòng quá

2021-12-02 23:24 UTC, closed without merging